"""Search client abstraction for ResearcherAgent."""

import json

from multi_agent_research_lab.core.schemas import SourceDocument
from multi_agent_research_lab.services.llm_client import LLMClient


class SearchClient:
    """Provider-agnostic search client — uses LLM mock when no Tavily key is set."""

    def search(self, query: str, max_results: int = 5) -> list[SourceDocument]:
        """Return synthetic sources generated by LLM when no real search key is available."""
        from multi_agent_research_lab.core.config import get_settings

        settings = get_settings()
        if settings.tavily_api_key and settings.tavily_api_key.strip():
            return self._tavily_search(query, max_results)
        return self._llm_mock_search(query, max_results)

    def _llm_mock_search(self, query: str, max_results: int) -> list[SourceDocument]:
        """Generate plausible synthetic sources via LLM."""
        num = min(max(3, max_results), 5)
        llm = LLMClient()
        system_prompt = (
            "You are a search engine simulator. Given a research query, generate realistic "
            f"search results as a JSON array of {num} objects. Each object must have these "
            "fields: 'title' (string), 'url' (string, a plausible https URL), 'snippet' "
            "(string, 2-3 sentences of relevant content). Return ONLY the JSON array, no "
            "other text."
        )
        user_prompt = f"Generate search results for: {query}"

        response = llm.complete(system_prompt, user_prompt)

        try:
            raw = response.content.strip()
            # Strip markdown code fences if present
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
            items = json.loads(raw)
            sources = []
            for item in items[:num]:
                sources.append(
                    SourceDocument(
                        title=item.get("title", "Untitled"),
                        url=item.get("url"),
                        snippet=item.get("snippet", ""),
                    )
                )
            return sources
        except (json.JSONDecodeError, KeyError, TypeError):
            # Fallback: return a single generic source
            return [
                SourceDocument(
                    title=f"Research on: {query}",
                    url=None,
                    snippet=response.content[:500],
                )
            ]

    def _tavily_search(self, query: str, max_results: int) -> list[SourceDocument]:
        """Real Tavily search (only called if API key is present)."""
        from tavily import TavilyClient  # type: ignore[import]

        from multi_agent_research_lab.core.config import get_settings

        settings = get_settings()
        client = TavilyClient(api_key=settings.tavily_api_key)
        results = client.search(query=query, max_results=max_results)
        sources = []
        for r in results.get("results", []):
            sources.append(
                SourceDocument(
                    title=r.get("title", ""),
                    url=r.get("url"),
                    snippet=r.get("content", ""),
                )
            )
        return sources
